
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project2-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project2
  template:
    metadata:
      labels:
        app: project2
    spec:
      containers:
      - name: project2
        image: quay.io/ran_ju_vincie/cs401_project2_0:86feafa
        ports:
        - containerPort: 5005
